name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Latest Tag
        id: get_tag
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment Tag
        id: increment_tag
        run: |
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          patch=$((patch + 1))
          new_tag="v${major}.${minor}.${patch}"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dirlayout.exe -v ./...

      - name: Zip the executable
        run: |
          zip build.zip dirlayout.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dirlayout-windows-zip
          path: dirlayout.zip

      - name: Create Release and Upload Asset
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.new_tag }}
          draft: false
          generateReleaseNotes: true
          artifacts: "dirlayout.exe"
          token: ${{ secrets.GITHUB_TOKEN }}

